# .github/ISSUE_TEMPLATE/access-request.yml
name: "Repository Update-Access Request"
description: "Use this form to request updated repository access to a repository."
title: "[Access/Update Request] for "
labels: ["access-request", "needs-review", "update-request"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following details to request repository access. 
        Ensure your GitHub username is correct. (Must be a Cisco CEC ID)

  - type: input
    id: github_username
    attributes:
      label: "GitHub/Cisco CEC ID"
      description: "What is your GitHub username? (e.g., email@cisco.com)"
      placeholder: "@username"
    validations:
      required: true

  - type: dropdown
    id: access_level
    attributes:
      label: "Requested Access Level"
      description: "What level of permission do you need?"
      options:
        - "Read (View code, open issues/PRs)"
        - "Triage (Manage issues and PRs)"
        - "Write (Push to branches)"
        - "Admin (Ownership/Administrator)"
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: "Reason for Access"
      description: "Please briefly explain why you need access to this repository and what you'll be working on."
    validations:
      required: true
